// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package kubelet_client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TopologyRequest struct {
	Topo                 string   `protobuf:"bytes,1,opt,name=topo,proto3" json:"topo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopologyRequest) Reset()         { *m = TopologyRequest{} }
func (m *TopologyRequest) String() string { return proto.CompactTextString(m) }
func (*TopologyRequest) ProtoMessage()    {}
func (*TopologyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_27b64a20f87a12ff, []int{0}
}
func (m *TopologyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopologyRequest.Unmarshal(m, b)
}
func (m *TopologyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopologyRequest.Marshal(b, m, deterministic)
}
func (dst *TopologyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyRequest.Merge(dst, src)
}
func (m *TopologyRequest) XXX_Size() int {
	return xxx_messageInfo_TopologyRequest.Size(m)
}
func (m *TopologyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyRequest proto.InternalMessageInfo

func (m *TopologyRequest) GetTopo() string {
	if m != nil {
		return m.Topo
	}
	return ""
}

type TopologyReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopologyReply) Reset()         { *m = TopologyReply{} }
func (m *TopologyReply) String() string { return proto.CompactTextString(m) }
func (*TopologyReply) ProtoMessage()    {}
func (*TopologyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_27b64a20f87a12ff, []int{1}
}
func (m *TopologyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopologyReply.Unmarshal(m, b)
}
func (m *TopologyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopologyReply.Marshal(b, m, deterministic)
}
func (dst *TopologyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyReply.Merge(dst, src)
}
func (m *TopologyReply) XXX_Size() int {
	return xxx_messageInfo_TopologyReply.Size(m)
}
func (m *TopologyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyReply.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyReply proto.InternalMessageInfo

func (m *TopologyReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*TopologyRequest)(nil), "kubelet_client.TopologyRequest")
	proto.RegisterType((*TopologyReply)(nil), "kubelet_client.TopologyReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	InformTopology(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*TopologyReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) InformTopology(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*TopologyReply, error) {
	out := new(TopologyReply)
	err := c.cc.Invoke(ctx, "/kubelet_client.Greeter/InformTopology", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	InformTopology(context.Context, *TopologyRequest) (*TopologyReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_InformTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).InformTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubelet_client.Greeter/InformTopology",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).InformTopology(ctx, req.(*TopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubelet_client.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InformTopology",
			Handler:    _Greeter_InformTopology_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_27b64a20f87a12ff) }

var fileDescriptor_api_27b64a20f87a12ff = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcb, 0x2e, 0x4d, 0x4a, 0xcd, 0x49, 0x2d, 0x89, 0x4f,
	0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0x51, 0x52, 0xe5, 0xe2, 0x0f, 0xc9, 0x2f, 0xc8, 0xcf, 0xc9, 0x4f,
	0xaf, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0x29, 0xc9, 0x2f, 0xc8,
	0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x34, 0xb9, 0x78, 0x11, 0xca, 0x0a,
	0x72, 0x2a, 0x85, 0x24, 0xb8, 0xd8, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0xa1, 0xea, 0x60,
	0x5c, 0xa3, 0x58, 0x2e, 0x76, 0xf7, 0xa2, 0xd4, 0xd4, 0x92, 0xd4, 0x22, 0xa1, 0x20, 0x2e, 0x3e,
	0xcf, 0xbc, 0xb4, 0xfc, 0xa2, 0x5c, 0x98, 0x5e, 0x21, 0x79, 0x3d, 0x54, 0xfb, 0xf5, 0xd0, 0x2c,
	0x97, 0x92, 0xc5, 0xad, 0xa0, 0x20, 0xa7, 0x52, 0x89, 0xc1, 0xc9, 0x98, 0x4b, 0x3a, 0x33, 0x5f,
	0x2f, 0xbd, 0xa8, 0x20, 0x59, 0x2f, 0xb5, 0x22, 0x31, 0xb7, 0x20, 0x27, 0xb5, 0x58, 0x2f, 0x23,
	0x35, 0x27, 0x27, 0xbf, 0x3c, 0xbf, 0x28, 0x27, 0xc5, 0x49, 0xc8, 0x1b, 0xa2, 0xdd, 0x19, 0xac,
	0x3b, 0x00, 0xe4, 0xe7, 0x00, 0xc6, 0x24, 0x36, 0xb0, 0xe7, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x12, 0xe2, 0x47, 0x94, 0x09, 0x01, 0x00, 0x00,
}
